[package]
name = "oxyhash"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.5"
bitcoincore-rpc = "0.19.0"
clap = { version = "4.5.31", features = ["derive"] }
dotenv = "0.15.0"
hex = "0.4.3"
